In [1]:
import numpy as np

In [2]:
arr1=np.eye(3)#this is used to create a identity matrix
arr1

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [3]:
arr2=np.zeros((4,3))#used to create an array of given  with all the elements 
arr2

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [4]:
arr3=np.ones((3,3))#this create an array withh every element one
arr3

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [5]:
l1=[1,2,3]
arr4=np.diag(l1)
arr4

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [48]:

arr = np.array([[1, 5, 6], [4, 7, 2]]) 
# maximum element of array 
print ("Largest element is:", arr.max()) 
print ("Row-wise maximum elements:", arr.max(axis = 1) ) #print the max element row wise
print("column-wise maximum elements: ",arr.max(axis=0))#prints max element column -wise from every column
print("Mean of the array: " ,np.mean(arr))#print mean of the entire array
print("Mean row-wise of the array: " ,np.mean(arr,axis=1))#print mean of the entire array
print("Mean of the array: " ,np.mean(arr,axis=0))#print mean of the entire array
print(np.average(arr))#this is same as mean but if we pass a array to find weight then it will multiply it element wise in order to give the average


Largest element is: 7
Row-wise maximum elements: [6 7]
column-wise maximum elements:  [4 7 6]
Mean of the array:  4.166666666666667
Mean row-wise of the array:  [4.         4.33333333]
Mean of the array:  [2.5 6.  4. ]
4.166666666666667


In [12]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
b=np.array([[10,11,12],[13,14,15],[16,17,18]])
#add two arrays but they should have same dimensions otherwise it will show an array 
print("Array sum: ",a+b)
#subtract two arrays
print("Array subtraction: \n",b-a)
#multiplication of two arrays
print("This does  Multiplication elementwise: \n",a*b)
#if we want to do multiplication matrix wise we will need dot function
print("Matrix Multiplication: \n",a.dot(b))


Array sum:  [[11 13 15]
 [17 19 21]
 [23 25 27]]
Array subtraction:  [[9 9 9]
 [9 9 9]
 [9 9 9]]
This does  Multiplication elementwise:  [[ 10  22  36]
 [ 52  70  90]
 [112 136 162]]
Matrix Multiplication: 
 [[ 84  90  96]
 [201 216 231]
 [318 342 366]]


In [47]:
ar=np.array(25) #0-d array /single element array
ar1=np.array([1,2,3,4])#1-D array 
ar2=np.array([[1,2,3],[4,5,6]])#2-D array 
ar3=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])#3-D array 
arH=np.array([1,2,3,5],ndmin=5)#creating an array of higher dimensions  ndmin is used to give the dimensions
# In this array the innermost dimension (5th dim) has 4 elements, the 4th dim has 1 element that is the vector, 
# the 3rd dim has 1 element that is the matrix with the vector, the 2nd dim has 1 element that is 3D array and 1st dim has 1 element that is a 4D array.
print(ar)
print(ar1)
print(ar2)
print(ar3)
print(arH)
print(arr)
print(np.bincount(ar1))
print ("Adding 1 to every element:", ar1 + 1)
print ("\nSubtracting 2 from each element:", ar1 - 2)

25
[1 2 3 4]
[[1 2 3]
 [4 5 6]]
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
[[[[[1 2 3 5]]]]]
[[1 5 6]
 [4 7 2]]
[0 1 1 1 1]
Adding 1 to every element: [2 3 4 5]

Subtracting 2 from each element: [-1  0  1  2]


In [15]:
# Create a sequence of integers 
# from 0 to 30 with steps of 5
f = np.arange(0, 30, 5) 
number = np.arange(10)
number2 = np.arange(5,15)
f
number
number2

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [21]:
print("This tells us about the shape of an array :" ,arr.shape)
print("This tells us about the number of rows in an array :" ,len(arr))
print("This tells us about the number of element in an array :" ,arr.size)


This tells us about the shape of an array : (2, 3)
This tells us about the length of an array : 2
This tells us about the size of an array : 6


In [22]:
g = np.linspace(0, 5, 10) 
print ("A sequential array with 10 values between 0 and 5:", g)

A sequential array with 10 values between 0 and 5: [0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]


In [23]:
newarr = arr3.astype('i')#The astype() function creates a copy of the array, and allows you to specify the data type as a parameter.
print(newarr)
print(newarr.dtype)

[[1 1 1]
 [1 1 1]
 [1 1 1]]
int32


In [28]:
print(ar2[1,:])
print(ar2[:,2])

[4 5 6]
[3 6]


In [29]:
ar3.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [30]:
ar3.reshape(-1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [34]:
ar1.reshape(2,-1)

array([[1, 2],
       [3, 4]])

In [40]:
np.array_split(ar3,5)#works even if there are not sufficent elements in the array 

[array([[[1, 2, 3],
         [4, 5, 6]]]),
 array([[[ 7,  8,  9],
         [10, 11, 12]]]),
 array([], shape=(0, 2, 3), dtype=int32),
 array([], shape=(0, 2, 3), dtype=int32),
 array([], shape=(0, 2, 3), dtype=int32)]

In [41]:
import numpy as np
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
arr=np.concatenate((arr1,arr2))
print(arr)
arr3 = np.array([[1, 2], [3, 4]])
arr4 = np.array([[5, 6], [7, 8]])
arr5 = np.concatenate((arr3, arr4), axis=1)#axis =0 means we concatenate column wise and axis =1 means row wise 
print(arr5)
#join using stack 
#Stacking is same as concatenation, the only difference is that stacking is done along a new axis
arr7=np.stack((arr1,arr2))
arr8=np.stack((arr1,arr2),axis=1)
arr9=np.hstack((arr1,arr2))
arr10=np.vstack((arr1,arr2))
print( arr7)
print(arr8)
print(arr9)
print(arr10)

[1 2 3 4 5 6]
[[1 2 5 6]
 [3 4 7 8]]
[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]
[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]


In [42]:
import numpy as np
arr=np.array([1,2,3,4])
print(arr.dtype)
arr1=np.array([2,3,4,5],dtype='S')# b represent byte representation
print(arr1)

arr2 = np.array([1, 2, 3, 4], dtype='i4')
print(arr2.dtype)
arr3 = np.array([1.1, 2.1, 3.1])
#alternate method to define the data type 
newarr = arr3.astype('i')#The astype() function creates a copy of the array, and allows you to specify the data type as a parameter.
print(newarr)
print(newarr.dtype)

int32
[b'2' b'3' b'4' b'5']
int32
[1 2 3]
int32


In [49]:
ra = np.random.random((5,6))
print(ra)

[[0.20162977 0.22684468 0.78094203 0.04446026 0.09810734 0.2737236 ]
 [0.86051249 0.72577396 0.91738735 0.45126176 0.72220348 0.81802412]
 [0.30804858 0.17139976 0.23771994 0.67636793 0.18914014 0.22565212]
 [0.2949127  0.96529499 0.7200735  0.44450041 0.21826863 0.01708152]
 [0.62067928 0.89996575 0.08982854 0.86644502 0.32566894 0.68892367]]
